In [1]:
import numpy as np

In [3]:
arreglo = np.arange(0,10)
arreglo
mayorescinco = arreglo > 5
mayorescinco

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [12]:
matris3x3 = np.random.randint(0,20,9).reshape(3,3)
media = matris3x3.mean()
mayor_media = matris3x3[ matris3x3 > media]
mayor_media

array([15, 19, 19, 13, 12])

In [37]:
elementos = np.random.randint(0,45,15)
elementos

rangos = elementos[[3,7]]
rangos 

array([39, 35])

In [42]:
variables = np.random.rand(8)
variables[variables > 0.3] = -1
variables



array([-1.        , -1.        ,  0.15133966,  0.25753934,  0.07508684,
       -1.        , -1.        ,  0.09941016])