In [1]:
import numpy as np

In [5]:
#vistas

arreglo = np.arange(10)
arreglo

view_arrgl = arreglo[0:]
view_arrgl[0:5] = [12,13,14,15,16]

arreglo

array([12, 13, 14, 15, 16,  5,  6,  7,  8,  9])

In [23]:
#Copia

elementos = np.arange(3,10)
elementos

copia_array = elementos.copy()
copia_array
copia_array[1:] = [6,9,12,15,18,21]
copia_array

print(f' arreglo original: {elementos} \n copia del arreglo ya modificado : {copia_array}')

 arreglo original: [3 4 5 6 7 8 9] 
 copia del arreglo ya modificado : [ 3  6  9 12 15 18 21]


In [22]:
matris3x3 = np.arange(0,9).reshape(3,3)
matris3x3

sub_matris = matris3x3[:, 1]
sub_matris[:] = [12,15,18]
sub_matris

matris3x3







array([[ 0, 12,  2],
       [ 3, 15,  5],
       [ 6, 18,  8]])

In [36]:
matris5x6 = np.arange(1,31).reshape(5,6)
matris5x6 
sub_matx = matris5x6[:,3]
sub_matx = sub_matx.copy()

sub_matx[1:] = [8,12,16,24]

matris5x6



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])