In [1]:
import numpy as np

In [5]:
#Filtros 
arr = np.arange(0,100)
arr = arr[arr % 7 == 0]
arr

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [9]:
matris4x4 = np.random.rand(16).reshape(4,4)
matris4x4
filtro = matris4x4 > 0.5
resultado= matris4x4[filtro]
resultado

array([0.79022808, 0.81090791, 0.77197704, 0.89731844, 0.78266984,
       0.55353869, 0.70092374])

In [12]:
elementos = np.arange(-10,10)
elementos = elementos[elementos < 0]
elementos

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [14]:
matris5x5 = np.random.randint(0,50,25).reshape(5,5)
matris5x5 = matris5x5[matris5x5 % 2 == 0]
matris5x5 

array([46,  4, 44,  0,  4, 16, 40, 12, 12, 42, 46, 44, 36])