In [1]:
import numpy as np

In [5]:
#Where 

aleatorios = np.random.rand(20)
aleatorios

mayores05 = np.where(aleatorios > 0.5)
mayores05

(array([ 0,  1,  3,  4,  5,  7,  8, 11, 12, 15, 18]),)

In [7]:
numeros = np.random.randint(0,20,10)
numeros

numeros_par = np.where(numeros % 2 == 0,0,numeros)
numeros_par

array([ 0,  0,  1,  7,  1,  1, 19, 17,  0, 17])

In [8]:
arr1 = np.random.randint(0,20,10)
arr2 = np.random.randint(0,20,10)

valor_a_b = np.where(arr1 > arr2,arr1,arr2)
valor_a_b

array([ 7, 19, 15, 17, 13, 18,  6, 12, 17, 13])

In [15]:
numeros_rad = np.arange(-10,11)
numeros_rad

absoluto = np.where(numeros_rad < 0 ,abs(numeros_rad),numeros_rad)
absoluto

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10])