In [1]:

import numpy as np


In [ ]:
#Matrices 
#Identidad
matris6x6 = np.arange(36).reshape(6,6)
matris6x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [14]:
#Tranpuesta 
matris4x5 = np.random.rand(20).reshape(4,5)
matris4x5.T

array([[0.72918719, 0.59289411, 0.05541864, 0.9843736 ],
       [0.96120169, 0.17989412, 0.52397729, 0.46910278],
       [0.69426764, 0.23086987, 0.14845349, 0.58990777],
       [0.3257347 , 0.09053306, 0.06248217, 0.65773918],
       [0.02050975, 0.6861898 , 0.23403574, 0.31015975]])

In [23]:
#Suma 
matris_one = np.random.randint(1,10,9).reshape(3,3)
matris_one
matris_two = np.random.randint(1,10,9).reshape(3,3)
matris_two

#print(f'matris uno :\n {matris_one}\n matris dos:\n {matris_two}')

suma = matris_one + matris_two
suma

print(f'matris uno :\n {matris_one}\n matris dos:\n {matris_two} \n suma de las dos matrices es : \n {suma}')


matris uno :
 [[1 8 9]
 [4 9 7]
 [8 6 5]]
 matris dos:
 [[2 4 6]
 [5 5 1]
 [3 1 4]] 
 suma de las dos matrices es : 
 [[ 3 12 15]
 [ 9 14  8]
 [11  7  9]]


In [31]:
#Multiplicacion

matris2x4 = np.arange(5,13).reshape(2,4)
matris2x4

matris4X3 = np.arange(2,14).reshape(4,3)
matris4X3

producto = matris2x4 @ matris4X3
producto

print(f'matris uno :\n {matris2x4}\n matris dos:\n {matris4X3} \n producto de las dos matrices es : \n {producto}')

matris uno :
 [[ 5  6  7  8]
 [ 9 10 11 12]]
 matris dos:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]] 
 producto de las dos matrices es : 
 [[184 210 236]
 [288 330 372]]
