In [1]:
import numpy as np

In [ ]:
#Metodos de agregacion
# suma 
matris5x5 = np.random.randint(0,50,25).reshape(5,5)
matris5x5
suma = np.sum(matris5x5)
print(f'la matris sumada es  \n {matris5x5} \n la suma es : {suma}')

la matris sumada es  
 [[44 29 32 48  5]
 [12 19  4  9 36]
 [14 22 49 26  3]
 [ 3 19 31 26  9]
 [19 30 34 32 15]] 
 la suma es : 570


In [6]:
#Maximo & Minimo

valores = np.random.randint(0,50,20)
valores
valor_max = np.max(valores)
valor_min = np.min(valores)

print(f'el arreglo es {valores} \n el valor maximo es : {valor_max} \n valor minimo es : {valor_min}')

el arreglo es [47 46 29 21 27 22 21 14 28 25 11 24 34 12 11  7 45 10 21  7] 
 el valor maximo es : 47 
 valor minimo es : 7


In [8]:
# Mediana & desviasion estandar 

matris6x4 = np.random.randint(2,40,24).reshape(6,4)
matris6x4
mediana = np.median(matris6x4)
desviasion = np.std(matris6x4)

print(f'matris usada es : \n {matris6x4} \n la mediana es : {mediana} \n la desviasion estandar  es : {desviasion}')

matris usada es : 
 [[17 12 14 31]
 [13  5 25 39]
 [11 39  2 37]
 [12 18 16  8]
 [ 6 36 17 11]
 [34 16 30  4]] 
 la mediana es : 16.0 
 la desviasion estandar  es : 11.64156525844642


In [10]:
#Suma del eje = 0(colum) y eje = 1(file)

matris4x4 = np.random.randint(2,30,16).reshape(4,4)
matris4x4
suma_colum = np.sum(matris4x4 , axis=0)
suma_fila = np.sum(matris4x4 , axis=1)

print(f'la matris usada es: \n {matris4x4} \n suma de columnas es: {suma_colum} \n suma de filas es: {suma_fila}')

la matris usada es: 
 [[28  2 23 25]
 [ 6 16 10 25]
 [22 28 12 21]
 [27 25 12 17]] 
 suma de columnas es: [83 71 57 88] 
 suma de filas es: [78 57 83 81]
