In [1]:
import numpy as np

In [ ]:
#Sub-arreglos o slicing
elementos = np.arange(0,19)
elementos

sub_mul_tres = np.array([i for i in elementos if i % 3 == 0])
sub_mul_tres 


array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
matriz = np.arange(0,25).reshape(5,5)
matriz

sub_mat = matriz[0:,1:4]
sub_mat

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [16]:
matriz_cuatro_cuatro = np.arange(16).reshape(4,4)
matriz_cuatro_cuatro

filas, columnas = matriz_cuatro_cuatro.shape
diagonal_secundaria_indices = np.arange(columnas -1,-1,-1)
diagonal_secundaria = matriz_cuatro_cuatro[np.arange(filas),diagonal_secundaria_indices]
diagonal_secundaria

array([ 3,  6,  9, 12])

In [18]:
arreglo = np.arange(20)
arreglo

sub_arreglo = arreglo[7:12]
sub_arreglo

array([ 7,  8,  9, 10, 11])